/* Die Fragenpaare des Spiels.
   Jedes Paar besteht aus zwei Fragen, deren Antworten sich aehneln koennen –
   muessen aber nicht. Keine Frage und kein Paar kommt doppelt vor.
   Der Host zieht ohne Zuruecklegen, siehe ziehePaar() in host.js. */
const PAIRS=[
  ["Wie viele Stunden hast du letzte Nacht geschlafen?","Wie viele Tassen Kaffee trinkst du am Tag?"],
  ["Wie viel Geld gibst du pro Woche für Essen aus?","Wie viel kostet dein Handyvertrag im Monat?"],
  ["Wie oft machst du pro Woche Sport?","Wie oft bestellst du pro Woche Essen?"],
  ["Wie viele Menschen wohnen in deinem Haushalt?","Wie viele richtig enge Freunde hast du?"],
  ["Wie viele Paar Schuhe besitzt du?","Wie viele Jacken hängen bei dir im Flur?"],
  ["Wie viele Kilometer fährst du am Tag?","Wie viele Schritte machst du am Tag?"],
  ["Wie viel Prozent Akku hat dein Handy gerade?","Wie viel Prozent deines Geldes sparst du?"],
  ["Wie alt warst du bei deinem ersten Kuss?","Wie alt warst du, als du zum ersten Mal allein verreist bist?"],
  ["Wie viele Stunden am Tag schaust du auf dein Handy?","Wie viele Stunden am Tag arbeitest du wirklich konzentriert?"],
  ["Wie viele Geschwister hast du?","Wie viele Haustiere hattest du in deinem Leben?"],
  ["Wie viele Sprachen sprichst du?","In wie vielen Ländern warst du schon?"],
  ["Wie viele Gläser Wasser trinkst du am Tag?","Wie viele Mahlzeiten isst du am Tag?"],
  ["Wie oft im Jahr gehst du zum Friseur?","Wie oft im Jahr gehst du zum Arzt?"],
  ["Wie viele Passwörter hast du im Kopf?","Wie viele Telefonnummern kennst du auswendig?"],
  ["Wie viele Wecker stellst du dir?","Wie oft drückst du morgens die Schlummertaste?"],
  ["Wie viele Fotos machst du im Urlaub an einem Tag?","Wie viele Fotos auf deinem Handy siehst du nie wieder an?"],
  ["Wie viele Bücher liest du im Jahr?","Wie viele Filme schaust du im Monat?"],
  ["Wie viele Tage im Jahr bist du krank?","Wie viele Tage Urlaub nimmst du am Stück?"],
  ["Wie viele Nachbarn kennst du mit Namen?","Wie viele Nachbarn grüßt du?"],
  ["Wie viele Paar Socken besitzt du?","Wie viele T-Shirts hast du im Schrank?"],
  ["Wie viel Trinkgeld gibst du im Restaurant?","Wie viel darf ein Kaffee für dich kosten?"],
  ["Wie viele Tabs hast du gerade offen?","Wie viele Apps laufen bei dir im Hintergrund?"],
  ["Wie alt ist dein Handy?","Wie alt ist dein Auto?"],
  ["Wie viele Kilometer läufst du in der Woche?","Wie viele Kilometer fährst du in der Woche Rad?"],
  ["Wie viele Kissen liegen auf deinem Bett?","Wie viele Decken hast du zuhause?"],
  ["Wie viele Menschen könntest du jetzt spontan anrufen?","Wie viele Menschen kennen deine Adresse?"],
  ["Wie viele Minuten brauchst du zum Einschlafen?","Wie lange bleibst du nach dem Wecker noch liegen?"],
  ["Wie viele ungelesene Mails hast du?","Wie viele ungelesene Nachrichten hast du?"],
  ["Wie viel würdest du für gute Schuhe ausgeben?","Was hat dein teuerstes Kleidungsstück gekostet?"],
  ["Wie viele Stunden Schlaf brauchst du wirklich?","Wie lange schläfst du am Wochenende?"],
  ["Wie schnell fährst du auf der Autobahn?","Wie schnell fährst du innerorts wirklich?"],
  ["Wie warm ist es bei dir in der Wohnung?","Ab wie viel Grad machst du die Heizung an?"],
  ["Wie oft wechselst du die Bettwäsche?","Wie oft saugst du?"],
  ["Wann gehst du normalerweise ins Bett?","Wann stehst du am Wochenende auf?"],
  ["Wie lange brauchst du morgens im Bad?","Wie lange brauchst du zur Arbeit?"],
  ["Wie lange hältst du es ohne Handy aus?","Wie lange hältst du es aus, ohne zu reden?"],
  ["Wann isst du zu Abend?","Wann machst du Feierabend?"],
  ["Wann fängt für dich das Wochenende an?","Wann fängt für dich der Abend an?"],
  ["Wann schaust du morgens zum ersten Mal aufs Handy?","Wann trinkst du deinen ersten Kaffee?"],
  ["Wie lange bleibst du auf einer Party?","Wie lange hältst du es bei einer Familienfeier aus?"],
  ["Wie lange dauert bei dir ein Telefonat?","Wie lange dauert bei dir ein Einkauf?"],
  ["Was ist dein Lieblings-Urlaubsland?","In welchem Land würdest du nie leben wollen?"],
  ["Nenne eine Stadt, die du liebst.","Nenne eine Stadt, die überbewertet ist."],
  ["Wo war dein letzter Urlaub?","Wo möchtest du unbedingt mal hin?"],
  ["Was ist dein Lieblingsplatz zuhause?","Wo im Haus bist du am seltensten?"],
  ["In welchem Raum verbringst du die meiste Zeit?","Welcher Raum ist bei dir am unordentlichsten?"],
  ["Wohin gehst du, wenn du Ruhe brauchst?","Wo kannst du am besten nachdenken?"],
  ["Welches Bundesland kennst du am besten?","In welchem Bundesland warst du noch nie?"],
  ["Nenne ein Land, dessen Essen du liebst.","Nenne ein Land, in das du auswandern würdest."],
  ["Wo kaufst du meistens ein?","Welchen Laden betrittst du nie?"],
  ["Welcher Ort erinnert dich an deine Kindheit?","Wo warst du das letzte Mal richtig glücklich?"],
  ["Welche Stadt möchtest du noch einmal besuchen?","In welcher Stadt warst du am längsten?"],
  ["Was ist dein Lieblingsgetränk?","Was trinkst du, wenn du krank bist?"],
  ["Was isst du am liebsten zum Frühstück?","Was isst du nachts, wenn du Hunger bekommst?"],
  ["Nenne etwas, das immer in deinem Kühlschrank ist.","Nenne etwas, das du nie kaufen würdest."],
  ["Was bestellst du an der Bar?","Was trinkst du, wenn du am nächsten Tag früh raus musst?"],
  ["Welche Pizza bestellst du?","Welchen Belag magst du überhaupt nicht?"],
  ["Was kochst du, wenn Besuch kommt?","Was kochst du, wenn du keine Lust hast?"],
  ["Was isst du, wenn du traurig bist?","Was isst du zur Belohnung?"],
  ["Welches Gemüse magst du nicht?","Was hast du als Kind nie gegessen?"],
  ["Was steht auf deinem Einkaufszettel immer drauf?","Was kaufst du immer, obwohl du es nicht brauchst?"],
  ["Wie trinkst du deinen Kaffee?","Was bestellst du im Café?"],
  ["Was kocht deine Familie am besten?","Welches Gericht kannst du am besten kochen?"],
  ["Welches Fast Food geht immer?","Was isst du nach einer langen Nacht?"],
  ["Welche Süßigkeit könntest du nie aufgeben?","Was liegt bei dir immer im Vorratsschrank?"],
  ["Was trinkst du zum Anstoßen?","Was trinkst du an Silvester?"],
  ["Was ist in deinem Kühlschrank abgelaufen?","Was findet man ganz hinten in deinem Schrank?"],
  ["Wen rufst du an, wenn etwas Gutes passiert ist?","Wer weiß am meisten über dich?"],
  ["Wer in deiner Familie ist dir am ähnlichsten?","Wer hat dich am meisten geprägt?"],
  ["Wen aus deiner Schulzeit würdest du gern wiedersehen?","Wen aus deiner Schulzeit hast du völlig vergessen?"],
  ["Wer kocht bei euch zuhause?","Wer räumt bei euch die Spülmaschine aus?"],
  ["Mit wem schreibst du am meisten?","Wen siehst du am seltensten, obwohl du ihn magst?"],
  ["Wer war dein erstes Vorbild?","Wen hast du als Kind bewundert?"],
  ["Nenne einen Promi, den du treffen möchtest.","Nenne einen Promi, den du nicht ausstehen kannst."],
  ["Mit welcher berühmten Person würdest du essen gehen?","Wen aus der Geschichte würdest du gern treffen?"],
  ["Welchen Lehrer hast du nie vergessen?","Wer hat dir am meisten beigebracht?"],
  ["Was ist dein größtes Talent?","Worin bist du überraschend schlecht?"],
  ["Was ist deine größte Angst?","Wovor hattest du als Kind Angst?"],
  ["Nenne ein Wort, das du viel zu oft benutzt.","Nenne ein Wort, das du nicht leiden kannst."],
  ["Was machst du als Erstes nach dem Aufstehen?","Was machst du als Letztes vor dem Schlafen?"],
  ["Was schiebst du immer auf?","Was erledigst du sofort?"],
  ["Worüber regst du dich zu schnell auf?","Was bringt dich sofort in gute Laune?"],
  ["Was ist deine schlechteste Angewohnheit?","Was würdest du gern öfter machen?"],
  ["Wobei kannst du richtig abschalten?","Was machst du, wenn dir langweilig ist?"],
  ["Was sagst du, wenn du dich erschreckst?","Was ist dein Lieblingsschimpfwort?"],
  ["Wofür stehst du früh auf?","Wofür würdest du eine Nacht durchmachen?"],
  ["Was hast du zuletzt verloren?","Was suchst du ständig in deiner Wohnung?"],
  ["Was kannst du einfach nicht wegwerfen?","Was hebst du auf, obwohl es kaputt ist?"],
  ["Worüber lachst du, obwohl es albern ist?","Was findest du lustig, andere aber nicht?"],
  ["Was kannst du besonders gut nachmachen?","Wessen Stimme kannst du imitieren?"],
  ["Was ist dein Glücksbringer?","Welche Zahl ist deine Glückszahl?"],
  ["Wovon träumst du immer wieder?","Was war dein seltsamster Traum?"],
  ["Was nimmst du auf eine einsame Insel mit?","Was hast du immer in der Tasche?"],
  ["Was ist das Teuerste, was du besitzt?","Was würdest du bei einem Brand als Erstes retten?"],
  ["Was liegt auf deinem Nachttisch?","Was liegt in deiner Hosentasche?"],
  ["Welches Möbelstück willst du loswerden?","Was in deiner Wohnung ist am ältesten?"],
  ["Über welches Geschenk hast du dich am meisten gefreut?","Welches Geschenk hast du weiterverschenkt?"],
  ["Welches Kleidungsstück trägst du am häufigsten?","Was hängt ungetragen in deinem Schrank?"],
  ["Was hast du zuletzt repariert?","Was ist bei dir gerade kaputt?"],
  ["Was war dein letzter Online-Kauf?","Was liegt gerade in deinem Warenkorb?"],
  ["Wofür sparst du gerade?","Was war deine letzte größere Anschaffung?"],
  ["Was war die beste Investition deines Lebens?","Wofür gibst du richtig gern Geld aus?"],
  ["Was war dein größter Fehlkauf?","Was bereust du gekauft zu haben?"],
  ["Was steht auf deiner Fensterbank?","Welche Pflanze hast du zuletzt eingehen lassen?"],
  ["Was liegt in deinem Handschuhfach?","Was liegt in deinem Kofferraum?"],
  ["Welchen Beruf wolltest du als Kind?","Welchen Beruf könntest du niemals machen?"],
  ["Welches Schulfach mochtest du am liebsten?","In welchem Schulfach warst du am schlechtesten?"],
  ["Was nervt dich an deinem Job?","Was würdest du an deinem Arbeitsplatz sofort ändern?"],
  ["Welchen Job würdest du gern einen Monat testen?","Was wärst du geworden, wenn alles möglich wäre?"],
  ["Was war dein erster Job?","Womit hast du dein erstes eigenes Geld verdient?"],
  ["Was machst du bei der Arbeit, wenn keiner hinschaut?","Womit vertreibst du dir die Zeit in langen Besprechungen?"],
  ["Welches Fach hättest du in der Schule gebraucht?","Was hättest du gern früher gelernt?"],
  ["Was ist dein Lieblingsfilm?","Welchen Film hast du am häufigsten gesehen?"],
  ["Welche Serie schaust du gerade?","Welche Serie hast du abgebrochen?"],
  ["Welche Musikrichtung hörst du am liebsten?","Welche Musik läuft bei dir im Auto?"],
  ["Welche App nutzt du am meisten?","Welche App würdest du sofort löschen?"],
  ["Welches Lied läuft bei dir in Dauerschleife?","Welches Lied kennst du komplett auswendig?"],
  ["Welchen Film kannst du mitsprechen?","Welchen Film hast du als Kind rauf und runter geschaut?"],
  ["Welche Serie würdest du noch mal von vorn schauen?","Welche Serie hat das beste Ende?"],
  ["Welches Buch hast du nie zu Ende gelesen?","Welches Buch würdest du weiterempfehlen?"],
  ["Welcher Song bringt dich sofort zum Tanzen?","Was läuft bei dir beim Putzen?"],
  ["Welchen Podcast hörst du?","Was hörst du beim Autofahren?"],
  ["Welches Spiel hast du am längsten gespielt?","Welches Spiel würdest du nie wieder anfassen?"],
  ["Welche App öffnest du morgens zuerst?","Welche App hast du zuletzt installiert?"],
  ["Welches Emoji benutzt du am meisten?","Welches Emoji verstehst du nicht?"],
  ["Wem folgst du, ohne es zuzugeben?","Welchen Kanal schaust du regelmäßig?"],
  ["Wie kommst du am liebsten in den Urlaub?","Welches Verkehrsmittel meidest du?"],
  ["Was packst du immer zuletzt ein?","Was vergisst du beim Packen immer?"],
  ["Woran erinnerst du dich vom letzten Urlaub zuerst?","Was war dein schönster Urlaubsmoment?"],
  ["Was nervt dich im Straßenverkehr am meisten?","Was nervt dich an deinen Nachbarn?"],
  ["Was hörst du im Stau?","Was machst du, wenn du irgendwo zu früh bist?"],
  ["Was war dein erstes Auto?","Welches Auto hättest du gern?"],
  ["Was ist dein Lieblingsfeiertag?","Welchen Feiertag findest du überflüssig?"],
  ["Welches Wetter magst du am liebsten?","Bei welchem Wetter bleibst du lieber zuhause?"],
  ["Was gehört für dich zu Weihnachten?","Was gibt es bei euch an Heiligabend zu essen?"],
  ["Wie feierst du deinen Geburtstag?","Was wünschst du dir zum Geburtstag?"],
  ["Was machst du an einem verregneten Sonntag?","Was machst du, wenn du einen Tag ganz für dich hast?"],
  ["Welche Jahreszeit magst du am liebsten?","In welcher Jahreszeit bist du am aktivsten?"],
  ["Worauf freust du dich im Sommer am meisten?","Was machst du beim ersten warmen Tag im Jahr?"],
  ["Welche Hausarbeit machst du am liebsten?","Welche Hausarbeit schiebst du ewig auf?"],
  ["Was räumst du zuerst auf, wenn Besuch kommt?","Was versteckst du, wenn Besuch kommt?"],
  ["Welches Körperteil tut dir gerade weh?","Welches Körperteil magst du an dir am liebsten?"],
  ["Was tust du für deine Gesundheit?","Was solltest du dringend öfter machen?"],
  ["Welches Tier wärst du gern?","Welches Tier würdest du niemals anfassen?"],
  ["Nenne eine Farbe, die dir gut steht.","Nenne eine Farbe, die du hässlich findest."],
  ["Was würdest du mit 1000 € sofort machen?","Wofür gibst du eindeutig zu viel Geld aus?"],
  ["Welche Superkraft hättest du gern?","Was würdest du gern können, ohne es zu lernen?"],
  ["Was würdest du als Erstes tun, wenn du unsichtbar wärst?","Was würdest du tun, wenn niemand dich verurteilen würde?"],
  ["Was wäre dein Künstlername?","Wie würdest du dein Haustier nennen?"],
  ["Welches Tier beschreibt dich am besten?","Welches Tier beschreibt deinen Chef?"],
  ["Wie willst du in Erinnerung bleiben?","Was sollen die Leute über dich sagen?"],
  ["Welche Erfindung fehlt dir?","Was nervt dich täglich, obwohl es lösbar wäre?"],
  ["Was ist dein Partytrick?","Was würdest du auf einer Bühne machen?"],
  ["Welchen Trend hast du nie verstanden?","Was war die schlimmste Mode deiner Jugend?"],
  ["Was würdest du deinem 16-jährigen Ich sagen?","Was würdest du im Rückblick anders machen?"],
  ["Was war dein erster Spitzname?","Wie nennt dich deine Familie?"],
  ["Was machst du, wenn der Strom ausfällt?","Was ist dein Notfallplan bei Langeweile?"]
];
