/* Die Fragenpaare des Spiels.
   Jeder Eintrag: [Frage A, Frage B, Kategorie].
   Die beiden Fragen eines Paares koennen zu aehnlichen Antworten fuehren –
   muessen aber nicht. Keine Frage und kein Paar kommt doppelt vor.
   Der Host waehlt die Kategorien und zieht daraus ohne Zuruecklegen (ziehePaar in host.js). */
const KATEGORIEN=[
  {id:"zahlen",name:"Zahlen & Mengen",emoji:"🔢"},
  {id:"alltag",name:"Alltag & Routine",emoji:"🏠"},
  {id:"essen",name:"Essen & Trinken",emoji:"🍽️"},
  {id:"orte",name:"Orte & Reisen",emoji:"🌍"},
  {id:"menschen",name:"Menschen",emoji:"👥"},
  {id:"ich",name:"Über dich",emoji:"🙂"},
  {id:"dinge",name:"Dinge & Geld",emoji:"💶"},
  {id:"arbeit",name:"Arbeit & Schule",emoji:"💼"},
  {id:"medien",name:"Medien",emoji:"🎬"},
  {id:"feste",name:"Feste & Jahreszeiten",emoji:"🎉"},
  {id:"fantasie",name:"Fantasie & Spaß",emoji:"✨"}
];

const PAIRS=[
  ["Wie viele Stunden hast du letzte Nacht geschlafen?","Wie viele Tassen Kaffee trinkst du am Tag?","zahlen"],
  ["Wie viel Geld gibst du pro Woche für Essen aus?","Wie viel kostet dein Handyvertrag im Monat?","zahlen"],
  ["Wie oft machst du pro Woche Sport?","Wie oft bestellst du pro Woche Essen?","zahlen"],
  ["Wie viele Menschen wohnen in deinem Haushalt?","Wie viele richtig enge Freunde hast du?","zahlen"],
  ["Wie viele Paar Schuhe besitzt du?","Wie viele Jacken hängen bei dir im Flur?","zahlen"],
  ["Wie viele Kilometer fährst du am Tag?","Wie viele Schritte machst du am Tag?","zahlen"],
  ["Wie viel Prozent Akku hat dein Handy gerade?","Wie viel Prozent deines Geldes sparst du?","zahlen"],
  ["Wie alt warst du bei deinem ersten Kuss?","Wie alt warst du, als du zum ersten Mal allein verreist bist?","zahlen"],
  ["Wie viele Stunden am Tag schaust du auf dein Handy?","Wie viele Stunden am Tag arbeitest du wirklich konzentriert?","zahlen"],
  ["Wie viele Geschwister hast du?","Wie viele Haustiere hattest du in deinem Leben?","zahlen"],
  ["Wie viele Sprachen sprichst du?","In wie vielen Ländern warst du schon?","zahlen"],
  ["Wie viele Gläser Wasser trinkst du am Tag?","Wie viele Mahlzeiten isst du am Tag?","zahlen"],
  ["Wie oft im Jahr gehst du zum Friseur?","Wie oft im Jahr gehst du zum Arzt?","zahlen"],
  ["Wie viele Passwörter hast du im Kopf?","Wie viele Telefonnummern kennst du auswendig?","zahlen"],
  ["Wie viele Wecker stellst du dir?","Wie oft drückst du morgens die Schlummertaste?","zahlen"],
  ["Wie viele Fotos machst du im Urlaub an einem Tag?","Wie viele Fotos auf deinem Handy siehst du nie wieder an?","zahlen"],
  ["Wie viele Bücher liest du im Jahr?","Wie viele Filme schaust du im Monat?","zahlen"],
  ["Wie viele Tage im Jahr bist du krank?","Wie viele Tage Urlaub nimmst du am Stück?","zahlen"],
  ["Wie viele Nachbarn kennst du mit Namen?","Wie viele Nachbarn grüßt du?","zahlen"],
  ["Wie viele Paar Socken besitzt du?","Wie viele T-Shirts hast du im Schrank?","zahlen"],
  ["Wie viel Trinkgeld gibst du im Restaurant?","Wie viel darf ein Kaffee für dich kosten?","zahlen"],
  ["Wie viele Tabs hast du gerade offen?","Wie viele Apps laufen bei dir im Hintergrund?","zahlen"],
  ["Wie alt ist dein Handy?","Wie alt ist dein Auto?","zahlen"],
  ["Wie viele Kilometer läufst du in der Woche?","Wie viele Kilometer fährst du in der Woche Rad?","zahlen"],
  ["Wie viele Kissen liegen auf deinem Bett?","Wie viele Decken hast du zuhause?","zahlen"],
  ["Wie viele Menschen könntest du jetzt spontan anrufen?","Wie viele Menschen kennen deine Adresse?","zahlen"],
  ["Wie viele Minuten brauchst du zum Einschlafen?","Wie lange bleibst du nach dem Wecker noch liegen?","zahlen"],
  ["Wie viele ungelesene Mails hast du?","Wie viele ungelesene Nachrichten hast du?","zahlen"],
  ["Wie viel würdest du für gute Schuhe ausgeben?","Was hat dein teuerstes Kleidungsstück gekostet?","zahlen"],
  ["Wie viele Stunden Schlaf brauchst du wirklich?","Wie lange schläfst du am Wochenende?","zahlen"],
  ["Wie schnell fährst du auf der Autobahn?","Wie schnell fährst du innerorts wirklich?","zahlen"],
  ["Wie warm ist es bei dir in der Wohnung?","Ab wie viel Grad machst du die Heizung an?","zahlen"],
  ["Wie oft wechselst du die Bettwäsche?","Wie oft saugst du?","alltag"],
  ["Wann gehst du normalerweise ins Bett?","Wann stehst du am Wochenende auf?","alltag"],
  ["Wie lange brauchst du morgens im Bad?","Wie lange brauchst du zur Arbeit?","alltag"],
  ["Wie lange hältst du es ohne Handy aus?","Wie lange hältst du es aus, ohne zu reden?","alltag"],
  ["Wann isst du zu Abend?","Wann machst du Feierabend?","alltag"],
  ["Wann fängt für dich das Wochenende an?","Wann fängt für dich der Abend an?","alltag"],
  ["Wann schaust du morgens zum ersten Mal aufs Handy?","Wann trinkst du deinen ersten Kaffee?","alltag"],
  ["Wie lange bleibst du auf einer Party?","Wie lange hältst du es bei einer Familienfeier aus?","alltag"],
  ["Wie lange dauert bei dir ein Telefonat?","Wie lange dauert bei dir ein Einkauf?","alltag"],
  ["Was machst du als Erstes nach dem Aufstehen?","Was machst du als Letztes vor dem Schlafen?","alltag"],
  ["Welche Hausarbeit machst du am liebsten?","Welche Hausarbeit schiebst du ewig auf?","alltag"],
  ["Was räumst du zuerst auf, wenn Besuch kommt?","Was versteckst du, wenn Besuch kommt?","alltag"],
  ["Welches Körperteil tut dir gerade weh?","Welches Körperteil magst du an dir am liebsten?","alltag"],
  ["Was tust du für deine Gesundheit?","Was solltest du dringend öfter machen?","alltag"],
  ["In welchem Raum verbringst du die meiste Zeit?","Welcher Raum ist bei dir am unordentlichsten?","alltag"],
  ["Was steht auf deiner Fensterbank?","Welche Pflanze hast du zuletzt eingehen lassen?","alltag"],
  ["Was ist dein Lieblingsgetränk?","Was trinkst du, wenn du krank bist?","essen"],
  ["Was isst du am liebsten zum Frühstück?","Was isst du nachts, wenn du Hunger bekommst?","essen"],
  ["Nenne etwas, das immer in deinem Kühlschrank ist.","Nenne etwas, das du nie kaufen würdest.","essen"],
  ["Was bestellst du an der Bar?","Was trinkst du, wenn du am nächsten Tag früh raus musst?","essen"],
  ["Welche Pizza bestellst du?","Welchen Belag magst du überhaupt nicht?","essen"],
  ["Was kochst du, wenn Besuch kommt?","Was kochst du, wenn du keine Lust hast?","essen"],
  ["Was isst du, wenn du traurig bist?","Was isst du zur Belohnung?","essen"],
  ["Welches Gemüse magst du nicht?","Was hast du als Kind nie gegessen?","essen"],
  ["Was steht auf deinem Einkaufszettel immer drauf?","Was kaufst du immer, obwohl du es nicht brauchst?","essen"],
  ["Wie trinkst du deinen Kaffee?","Was bestellst du im Café?","essen"],
  ["Was kocht deine Familie am besten?","Welches Gericht kannst du am besten kochen?","essen"],
  ["Welches Fast Food geht immer?","Was isst du nach einer langen Nacht?","essen"],
  ["Welche Süßigkeit könntest du nie aufgeben?","Was liegt bei dir immer im Vorratsschrank?","essen"],
  ["Was trinkst du zum Anstoßen?","Was trinkst du an Silvester?","essen"],
  ["Was ist in deinem Kühlschrank abgelaufen?","Was findet man ganz hinten in deinem Schrank?","essen"],
  ["Was ist dein Lieblings-Urlaubsland?","In welchem Land würdest du nie leben wollen?","orte"],
  ["Nenne eine Stadt, die du liebst.","Nenne eine Stadt, die überbewertet ist.","orte"],
  ["Wo war dein letzter Urlaub?","Wo möchtest du unbedingt mal hin?","orte"],
  ["Was ist dein Lieblingsplatz zuhause?","Wo im Haus bist du am seltensten?","orte"],
  ["Wohin gehst du, wenn du Ruhe brauchst?","Wo kannst du am besten nachdenken?","orte"],
  ["Welches Bundesland kennst du am besten?","In welchem Bundesland warst du noch nie?","orte"],
  ["Nenne ein Land, dessen Essen du liebst.","Nenne ein Land, in das du auswandern würdest.","orte"],
  ["Wo kaufst du meistens ein?","Welchen Laden betrittst du nie?","orte"],
  ["Welcher Ort erinnert dich an deine Kindheit?","Wo warst du das letzte Mal richtig glücklich?","orte"],
  ["Welche Stadt möchtest du noch einmal besuchen?","In welcher Stadt warst du am längsten?","orte"],
  ["Wie kommst du am liebsten in den Urlaub?","Welches Verkehrsmittel meidest du?","orte"],
  ["Was packst du immer zuletzt ein?","Was vergisst du beim Packen immer?","orte"],
  ["Woran erinnerst du dich vom letzten Urlaub zuerst?","Was war dein schönster Urlaubsmoment?","orte"],
  ["Was nervt dich im Straßenverkehr am meisten?","Was nervt dich an deinen Nachbarn?","orte"],
  ["Was hörst du im Stau?","Was machst du, wenn du irgendwo zu früh bist?","orte"],
  ["Was war dein erstes Auto?","Welches Auto hättest du gern?","orte"],
  ["Was liegt in deinem Handschuhfach?","Was liegt in deinem Kofferraum?","orte"],
  ["Wen rufst du an, wenn etwas Gutes passiert ist?","Wer weiß am meisten über dich?","menschen"],
  ["Wer in deiner Familie ist dir am ähnlichsten?","Wer hat dich am meisten geprägt?","menschen"],
  ["Wen aus deiner Schulzeit würdest du gern wiedersehen?","Wen aus deiner Schulzeit hast du völlig vergessen?","menschen"],
  ["Wer kocht bei euch zuhause?","Wer räumt bei euch die Spülmaschine aus?","menschen"],
  ["Mit wem schreibst du am meisten?","Wen siehst du am seltensten, obwohl du ihn magst?","menschen"],
  ["Wer war dein erstes Vorbild?","Wen hast du als Kind bewundert?","menschen"],
  ["Nenne einen Promi, den du treffen möchtest.","Nenne einen Promi, den du nicht ausstehen kannst.","menschen"],
  ["Mit welcher berühmten Person würdest du essen gehen?","Wen aus der Geschichte würdest du gern treffen?","menschen"],
  ["Welchen Lehrer hast du nie vergessen?","Wer hat dir am meisten beigebracht?","menschen"],
  ["Was war dein erster Spitzname?","Wie nennt dich deine Familie?","menschen"],
  ["Was ist dein größtes Talent?","Worin bist du überraschend schlecht?","ich"],
  ["Was ist deine größte Angst?","Wovor hattest du als Kind Angst?","ich"],
  ["Nenne ein Wort, das du viel zu oft benutzt.","Nenne ein Wort, das du nicht leiden kannst.","ich"],
  ["Was schiebst du immer auf?","Was erledigst du sofort?","ich"],
  ["Worüber regst du dich zu schnell auf?","Was bringt dich sofort in gute Laune?","ich"],
  ["Was ist deine schlechteste Angewohnheit?","Was würdest du gern öfter machen?","ich"],
  ["Wobei kannst du richtig abschalten?","Was machst du, wenn dir langweilig ist?","ich"],
  ["Was sagst du, wenn du dich erschreckst?","Was ist dein Lieblingsschimpfwort?","ich"],
  ["Wofür stehst du früh auf?","Wofür würdest du eine Nacht durchmachen?","ich"],
  ["Was hast du zuletzt verloren?","Was suchst du ständig in deiner Wohnung?","ich"],
  ["Was kannst du einfach nicht wegwerfen?","Was hebst du auf, obwohl es kaputt ist?","ich"],
  ["Worüber lachst du, obwohl es albern ist?","Was findest du lustig, andere aber nicht?","ich"],
  ["Was kannst du besonders gut nachmachen?","Wessen Stimme kannst du imitieren?","ich"],
  ["Was ist dein Glücksbringer?","Welche Zahl ist deine Glückszahl?","ich"],
  ["Wovon träumst du immer wieder?","Was war dein seltsamster Traum?","ich"],
  ["Was nimmst du auf eine einsame Insel mit?","Was hast du immer in der Tasche?","dinge"],
  ["Was ist das Teuerste, was du besitzt?","Was würdest du bei einem Brand als Erstes retten?","dinge"],
  ["Was liegt auf deinem Nachttisch?","Was liegt in deiner Hosentasche?","dinge"],
  ["Welches Möbelstück willst du loswerden?","Was in deiner Wohnung ist am ältesten?","dinge"],
  ["Über welches Geschenk hast du dich am meisten gefreut?","Welches Geschenk hast du weiterverschenkt?","dinge"],
  ["Welches Kleidungsstück trägst du am häufigsten?","Was hängt ungetragen in deinem Schrank?","dinge"],
  ["Was hast du zuletzt repariert?","Was ist bei dir gerade kaputt?","dinge"],
  ["Was war dein letzter Online-Kauf?","Was liegt gerade in deinem Warenkorb?","dinge"],
  ["Wofür sparst du gerade?","Was war deine letzte größere Anschaffung?","dinge"],
  ["Was war die beste Investition deines Lebens?","Wofür gibst du richtig gern Geld aus?","dinge"],
  ["Was war dein größter Fehlkauf?","Was bereust du gekauft zu haben?","dinge"],
  ["Welchen Beruf wolltest du als Kind?","Welchen Beruf könntest du niemals machen?","arbeit"],
  ["Welches Schulfach mochtest du am liebsten?","In welchem Schulfach warst du am schlechtesten?","arbeit"],
  ["Was nervt dich an deinem Job?","Was würdest du an deinem Arbeitsplatz sofort ändern?","arbeit"],
  ["Welchen Job würdest du gern einen Monat testen?","Was wärst du geworden, wenn alles möglich wäre?","arbeit"],
  ["Was war dein erster Job?","Womit hast du dein erstes eigenes Geld verdient?","arbeit"],
  ["Was machst du bei der Arbeit, wenn keiner hinschaut?","Womit vertreibst du dir die Zeit in langen Besprechungen?","arbeit"],
  ["Welches Fach hättest du in der Schule gebraucht?","Was hättest du gern früher gelernt?","arbeit"],
  ["Was ist dein Lieblingsfilm?","Welchen Film hast du am häufigsten gesehen?","medien"],
  ["Welche Serie schaust du gerade?","Welche Serie hast du abgebrochen?","medien"],
  ["Welche Musikrichtung hörst du am liebsten?","Welche Musik läuft bei dir im Auto?","medien"],
  ["Welche App nutzt du am meisten?","Welche App würdest du sofort löschen?","medien"],
  ["Welches Lied läuft bei dir in Dauerschleife?","Welches Lied kennst du komplett auswendig?","medien"],
  ["Welchen Film kannst du mitsprechen?","Welchen Film hast du als Kind rauf und runter geschaut?","medien"],
  ["Welche Serie würdest du noch mal von vorn schauen?","Welche Serie hat das beste Ende?","medien"],
  ["Welches Buch hast du nie zu Ende gelesen?","Welches Buch würdest du weiterempfehlen?","medien"],
  ["Welcher Song bringt dich sofort zum Tanzen?","Was läuft bei dir beim Putzen?","medien"],
  ["Welchen Podcast hörst du?","Was hörst du beim Autofahren?","medien"],
  ["Welches Spiel hast du am längsten gespielt?","Welches Spiel würdest du nie wieder anfassen?","medien"],
  ["Welche App öffnest du morgens zuerst?","Welche App hast du zuletzt installiert?","medien"],
  ["Welches Emoji benutzt du am meisten?","Welches Emoji verstehst du nicht?","medien"],
  ["Wem folgst du, ohne es zuzugeben?","Welchen Kanal schaust du regelmäßig?","medien"],
  ["Was ist dein Lieblingsfeiertag?","Welchen Feiertag findest du überflüssig?","feste"],
  ["Welches Wetter magst du am liebsten?","Bei welchem Wetter bleibst du lieber zuhause?","feste"],
  ["Was gehört für dich zu Weihnachten?","Was gibt es bei euch an Heiligabend zu essen?","feste"],
  ["Wie feierst du deinen Geburtstag?","Was wünschst du dir zum Geburtstag?","feste"],
  ["Was machst du an einem verregneten Sonntag?","Was machst du, wenn du einen Tag ganz für dich hast?","feste"],
  ["Welche Jahreszeit magst du am liebsten?","In welcher Jahreszeit bist du am aktivsten?","feste"],
  ["Worauf freust du dich im Sommer am meisten?","Was machst du beim ersten warmen Tag im Jahr?","feste"],
  ["Welches Tier wärst du gern?","Welches Tier würdest du niemals anfassen?","fantasie"],
  ["Nenne eine Farbe, die dir gut steht.","Nenne eine Farbe, die du hässlich findest.","fantasie"],
  ["Was würdest du mit 1000 € sofort machen?","Wofür gibst du eindeutig zu viel Geld aus?","fantasie"],
  ["Welche Superkraft hättest du gern?","Was würdest du gern können, ohne es zu lernen?","fantasie"],
  ["Was würdest du als Erstes tun, wenn du unsichtbar wärst?","Was würdest du tun, wenn niemand dich verurteilen würde?","fantasie"],
  ["Was wäre dein Künstlername?","Wie würdest du dein Haustier nennen?","fantasie"],
  ["Welches Tier beschreibt dich am besten?","Welches Tier beschreibt deinen Chef?","fantasie"],
  ["Wie willst du in Erinnerung bleiben?","Was sollen die Leute über dich sagen?","fantasie"],
  ["Welche Erfindung fehlt dir?","Was nervt dich täglich, obwohl es lösbar wäre?","fantasie"],
  ["Was ist dein Partytrick?","Was würdest du auf einer Bühne machen?","fantasie"],
  ["Welchen Trend hast du nie verstanden?","Was war die schlimmste Mode deiner Jugend?","fantasie"],
  ["Was würdest du deinem 16-jährigen Ich sagen?","Was würdest du im Rückblick anders machen?","fantasie"],
  ["Was machst du, wenn der Strom ausfällt?","Was ist dein Notfallplan bei Langeweile?","fantasie"]
];
